; PCB GCode generated by RepRap Java Host Software
; Created: 2015-09-24:20-54-54
; Gerber tracks and pads file: hotbed.top
; Drill file: hotbed.tdr
;#!RECTANGLE: <BOX x:[l:10.0, h:14.311024999999999], y:[l:10.0, h:14.330710000000002]>
;#!LAYER: 1/1
G21 ;metric
G90 ;absolute positioning
M140 S0.0 ;set bed temperature and return
T1; select new extruder
G28; go home
G92 E0 ;zero the extruded length
G1 F50.0; Z feedrate
G1 Z0.0; Z clearance height
G1 F1500.0; XY feedrate
M0 ; stop RepRap
